name: release and push to central
on:
  push:
    branches:
      - test
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
      - name: Docker build
        run: |
          docker build . -t epos/epos-api-gateway-test:latest
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker push
        run: |
          docker push epos/epos-api-gateway-test:latest